apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: "CDRO Actions"
inputs:
  type:
    description: 'DSL or YAML files (default "groovy")'
    required: false
    default: groovy
  url:
    description: 'CDRO URL'
    required: false
    default: 'https://sda.preview.cb-demos.io'
  username:
    description: 'CDRO Username'
    required: true
  user-token:
    description: 'CDRO User token'
    required: true
  file:
    description: 'DSL/YAML file in workspace to run'
    required: true
outputs:
    results_json:
      description: 'JSON results from DSL/YAML file'
      value: ${{steps.invoke-cdrodsl-action.outputs.results_json}}

runs:
  using: composite
  steps:
    - id: invoke-cdrodsl-action
      name: evalDSL
      uses: docker://rbroker/cdro-cli:latest
      shell: sh
      run: |
        /app/cdro-cli --url ${{ inputs.url }} \
                      --username ${{ inputs.username }} \
                      --password ${{ inputs.user-token }} \
                      --file ${{ inputs.file }}  > results.json

        cat results.json > $CLOUDBEES_OUTPUTS/results_json
        cat results.json
 
