apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: "CDRO Actions"
inputs:
  type:
    description: 'DSL or YAML files (default "groovy")'
    required: false
    default: groovy
  url:
    description: 'CDRO URL'
    required: false
    default: 'https://sda.preview.cb-demos.io'
  username:
    description: 'CDRO Username'
    required: true
  user-token:
    description: 'CDRO User token'
    required: true
  file:
    description: 'DSL/YAML file in workspace to run'
    required: true


runs:
  using: composite
  steps:
    - id: invoke-cdrodsl-action
      name: evalDSL
      uses: docker://fedora:39
      shell: sh
      run: |
        #set -x
        mkdir /app
        cd /app
        curl -o cdro-cli https://github.com/zvercodebender/cdro-cli/releases/download/0.5/cdro-cli-linux-amd64
        chmod +x cdro-cli
        cd /cloudbees/workspace
        /app/cdro-cli --url ${{ inputs.url }} \
                      --username ${{ inputs.username }} \
                      --password ${{ inputs.user-token }} \
                      --file ${{ inputs.file }} \\
                      --output result.json
        cat result.json
        