apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: "CDRO Actions"
inputs:
  type:
    description: 'DSL or YAML files (default "groovy")'
    required: false
    default: groovy
  url:
    description: 'CDRO URL'
    required: false
    default: 'https://sda.preview.cb-demos.io'
  username:
    description: 'CDRO Username'
    required: true
  user-token:
    description: 'CDRO User token'
    required: true
  file:
    description: 'DSL/YAML file in workspace to run'
    required: true
# outputs:
#     results_json: ${{steps.invoke-cdrodsl-action.outputs.results_json}}
#     testproperty: ${{steps.invoke-cdrodsl-action.outputs.testpropertyn}}

runs:
  using: composite
  steps:
    - id: invoke-cdrodsl-action
      name: evalDSL
      uses: docker://rbroker/cdro-cli:latest
      shell: sh
      run: |
        /app/cdro-cli --url ${{ inputs.url }} \
                      --username ${{ inputs.username }} \
                      --password ${{ inputs.user-token }} \
                      --file ${{ inputs.file }}  > results.json

        cat results.json >> "$CLOUDBEES_OUTPUTS/results_json"
        cat results.json
        echo " date +%Y%m%d%H%M" >> "$CLOUDBEES_OUTPUTS/testproperty"
        echo " date +%Y%m%d%H%M"

