apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "docker"

jobs:
  build-and-publish:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Set Version
        id: set-tag
        uses: docker://fedora:39
        shell: sh
        run: |
          dnf install -y git > /dev/null
          DATE=`date '+%y%m%d'`
          HASH=`git rev-parse --short HEAD`
          echo "Working on tag ~${DATE}.${HASH}~"
          echo -n "${DATE}.${HASH}" >> "$CLOUDBEES_OUTPUTS/version_tag" 

      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build a container image with Kaniko
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: container/Dockerfile
          context: .
          destination: rbroker/cdro-cli:${{steps.set-tag.outputs.version_tag}},rbroker/cdro-cli:latest
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1,BUILDKIT_INLINE_CACHE=1"

