apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout
      - uses: zvercodebender/cdrodsl-action/dslEval@v0.4
        name: evalDSL
        id: invoke-cdrodsl-action
        with:
          url: ${{ vars.CB_FLOW }}
          username: ${{secrets.CB_USER}}
          user-token: ${{secrets.CB_PASSWD}}
          file: test.dsl
      - uses: docker://fedora:39
        name: showJSON
        id: showJSON
        shell: sh
        run: |
          echo "==========="
          echo "${{steps.invoke-cdrodsl-action.outputs.results_json}}"
          echo "==========="

      - name: Run Procedure
        uses: zvercodebender/cdrodsl-action/run-procedure@v1
        with:
          url: ${{ vars.CB_FLOW }}
          username: ${{secrets.CB_USER}}
          user-token: ${{secrets.CB_PASSWD}}
          projectName: My project
          procedureName: My procedure
          actualParameter: |
            param1: param1 value
            param2: 1.0

