apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout
      - uses: zvercodebender/cdrodsl-action/dslEval@v0.2
        name: evalDSL
        with:
          url: ${{ vars.CB_FLOW }}
          username: ${{secrets.CB_USER}}
          user-token: ${{secrets.CB_PASSWD}}
          file: test.dsl
    # outputs:
    #   results_json: ${{ steps.action.outputs.results_json }}
