apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "main"
jobs:
  build-and-publish:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: evalDSL
        uses: zvercodebender/cdrodsl-action/dslEval@v0.2
        with:
          url: "${{ vars.CB_FLOW }}"
          username: ${{secrets.CB_USER}}
          user-token: ${{secrets.CB_PASSWD}}
          file: "test.dsl"
# Test 1